[files]
extend-exclude = [
    "src/content/docs/arc-standards/arc-*.md",
    "src/content/docs/reference/algokit-utils-ts/API Reference/**/*",
    "src/content/docs/reference/algorand-python/API Reference/**/*",
    "src/content/docs/reference/algokit-utils-py/API Reference/**/*",
]

[default.extend-words]
Allo = "Allo"
optin = "optin"
asnd = "asnd"

[default]
extend-ignore-re = [
  "(?i)[A-Z2-7]{26,}",  # Matches base32-encoded strings
]