name: Documentation Feedback
description: Provide feedback on our documentation.
title: '[Feedback]: '
labels: ['feedback']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback on our documentation! Your input is invaluable in helping us improve.
  - type: textarea
    id: content-url
    attributes:
      label: Content URLs
      description: Please provide the URL(s) of the documentation page(s) you are providing feedback on.
    validations:
      required: false
  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback do you have?\
      multiple: true
      options:
        - Inaccuracy
        - Confusing explanation
        - Missing reference info
        - Code example needed
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Please describe the problem you encountered in detail.
    validations:
      required: true
