name: Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches: [staging]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install D2
        run: |
          curl -fsSL https://d2lang.com/install.sh | sh

      - name: Install dependencies and build the site
        run: |
          pnpm install
          pnpm run build

      - name: Upload your site
        uses: withastro/action@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging-env
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Staging
        id: deployment
        uses: actions/deploy-pages@v4
